import numpy as np
arr=np.arange(1,11)
print("Array:",arr)
Sum=np.sum(arr)
print("sum:",Sum)
product=np.prod(arr)
print("product:",product)
Min=np.min(arr)
print("Minimum value:",Min)
Max=np.max(arr)
print("Maximum:",Max)
Mean=np.mean(arr)
print("Mean:",Mean)
Median=np.median(arr)
print("Median:",Median)
Variance=np.var(arr)
print("Veriance:",Variance)
Std=np.std(arr)
print("Standard:",Std)